server:
  port: 8081

spring:
  application:
    name: user

  datasource:
#    url: jdbc:postgresql://172.18.0.2:5433/users
    url: jdbc:postgresql://localhost:5433/users
    username: 'coachme'
    password: 'root'

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

